name: Run update-since-todo.py

on:
  schedule:
    - cron: "0 16 * * THU"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run_script:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'jenkinsci' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run update-since-todo.py
        run: |
          body=$(./update-since-todo.py)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "PROGRESS=$body" >> $GITHUB_OUTPUT
        id: run_script
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Fill in since annotations
          title: Fill in since annotations
          body: ${{ steps.run_script.outputs.PROGRESS }}
          base: master
          labels: skip-changelog
          delete-branch: true
